version: "3.7"
services:
    db:
        container_name: the-coding-owl_core_db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: the-coding-owl-core
        ports:
            - "3306:3306"
        volumes:
            - mysqlDb:/var/lib/mysql
volumes:
    mysqlDb:
